name: Update WakaTime Stats in README

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC
  workflow_dispatch: # Allow manual run

permissions:
  contents: write

jobs:
  update-wakatime:
    runs-on: ubuntu-latest
    name: Update WakaTime data

    steps:
      - uses: actions/checkout@v4

      - name: WakaTime Readme Stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          commit_message: "Updated WakaTime stats 📈"
          show_title: true
          show_time: true
          show_total: true
          time_range: last_7_days
          lang_count: 5
